# get version
version: "3.8"

#define networks
networks:
  my_network:
    driver: bridge

# define services

services:
  my_nginx:
    container_name: nginx_test
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - db
    networks:
      - my_network

  db:
    container_name: mysql_test
    image: mysql:8.3.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - my_network

  php:
    container_name: php_test
    image: php:8.2-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - my_network
